ARG JAVA_VERSION=17
FROM maven:3.9.5-eclipse-temurin-${JAVA_VERSION}

ENV NOME_JAR=demo
ENV VERSAO_JAR=0.0.1-SNAPSHOT
ENV NOME_USUARIO=rotasegura

RUN adduser -D ${NOME_USUARIO}

WORKDIR /home/${NOME_USUARIO}/app

COPY . .

RUN mvn clean install -DskipTests

COPY target/${NOME_JAR}-${VERSAO_JAR}.jar app.jar

USER ${NOME_USUARIO}

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]
